try{
    let a=0;
    console.log(program)
    console.log("program run successfully")
}
catch(error)
{
    console.log("This is an error")
    console.log(program)
}
finally{
    console.log("heyyyyyyy thank u")
}